[global]
debug = false

[gunicorn]
bind = "0.0.0.0:8080"
workers = 2
timeout = 30
worker_class = "uvicorn.workers.UvicornWorker"

[database]
host = "localhost"
port = "5432"
name = "rksi2025"
user = "postgres"
password = "postgres"

[redis]
host = "localhost"
port = 6379

[smtp]
smtp_password = "aaaa bbbb cccc dddd"
smtp_user = "rksi@hack.ru"
smtp_host = "smtp.gmail.com"
smtp_port = 465
