services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=race_simulation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: backend
    command: [ "sh", "/backend/docker/serve.sh" ]
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
      - db

  migrations:
    profiles: [ "migration" ]
    build:
      context: backend
    command: [ "sh", "/backend/docker/migrate.sh" ]
    volumes:
      - ./backend:/backend
    depends_on:
      - db

#  frontend:
#    build:
#      context: frontend
#    volumes:
#      - ./build:/app/dist

#  nginx:
#    build:
#      context: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./build:/var/www/build
#      - ./backend/static:/var/www/static
#      - ./nginx/letsencrypt:/etc/letsencrypt
#      - ./nginx/webroot:/var/www/certbot
#    depends_on:
#      - backend
#
#  certbot:
#    image: certbot/certbot:v3.2.0
#    volumes:
#      - ./nginx/letsencrypt:/etc/letsencrypt
#      - ./nginx/webroot:/var/www/certbot
#    depends_on:
#      - nginx
